project_id = "siadshsaiuecesydqzqo"

[functions.notify-drivers-new-ride]
verify_jwt = false

[functions.create-ride-and-notify-drivers]
verify_jwt = false

[functions.get-firebase-config]
verify_jwt = false

[functions.send-fcm-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.charge-tip]
verify_jwt = false